apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fileupdatestest-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fileupdatestest/fileupdatestest-component@sha256:e80b589c8276762101ef48c4be4a1900a64c7b71dd344c22f0d330cf0b050e7a
        name: my-python
        resources: {}
status: {}
